# Generated by Django 4.1.2 on 2022-12-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
